import type { Mode, ModeKey } from '@/types';

export const MODES: Mode[] = [
  // ── Classiques majeurs ──
  {
    key: 'ionian',
    name: 'Ionien',
    intervals: [2, 2, 1, 2, 2, 2, 1],
    chord: 'maj7',
    desc: 'Le majeur classique, sage',
    category: 'classique_majeur',
    examples: [
      { song: 'Let It Be', artist: 'The Beatles', note: 'C ionien' },
      { song: 'Ode to Joy', artist: 'Beethoven', note: 'ré majeur' },
      { song: 'Happy Birthday', artist: 'traditionnel' },
    ],
  },
  {
    key: 'lydian',
    name: 'Lydien',
    intervals: [2, 2, 2, 1, 2, 2, 1],
    chord: 'maj7#11',
    desc: 'Lumineux, flottant',
    category: 'classique_majeur',
    examples: [
      { song: 'Flying in a Blue Dream', artist: 'Joe Satriani', note: 'A lydien' },
      { song: 'Misty Mountain Hop', artist: 'Led Zeppelin', note: 'riff en A lydien' },
      { song: 'Flying', artist: 'The Beatles', note: 'instrumental, A lydien' },
    ],
  },
  {
    key: 'mixolydian',
    name: 'Mixolydien',
    intervals: [2, 2, 1, 2, 2, 1, 2],
    chord: '7',
    desc: 'Blues, dominant',
    category: 'classique_majeur',
    examples: [
      { song: 'Norwegian Wood', artist: 'The Beatles', note: 'E mixolydien' },
      { song: 'Sympathy for the Devil', artist: 'Rolling Stones', note: 'B mixolydien' },
      { song: 'Baba O\'Riley', artist: 'The Who', note: 'F mixolydien, synthé d\'intro' },
    ],
  },
  // ── Classiques mineurs ──
  {
    key: 'dorian',
    name: 'Dorien',
    intervals: [2, 1, 2, 2, 2, 1, 2],
    chord: 'm7',
    desc: 'Mineur jazz, ouvert',
    category: 'classique_mineur',
    examples: [
      { song: 'Oye Como Va', artist: 'Carlos Santana', note: 'A dorien' },
      { song: 'Scarborough Fair', artist: 'Simon & Garfunkel', note: 'E dorien' },
      { song: 'So What', artist: 'Miles Davis', note: 'D dorien / Eb dorien' },
    ],
  },
  {
    key: 'phrygian',
    name: 'Phrygien',
    intervals: [1, 2, 2, 2, 1, 2, 2],
    chord: 'm7',
    desc: 'Sombre, couleur espagnole',
    category: 'classique_mineur',
    examples: [
      { song: 'Wherever I May Roam', artist: 'Metallica', note: 'E phrygien' },
      { song: 'La Macarena', artist: 'Los Del Rio', note: 'couleur phrygienne' },
      { song: 'flamenco (general)', artist: 'Paco de Lucía', note: 'E phrygien' },
    ],
  },
  {
    key: 'aeolian',
    name: 'Aeolien',
    intervals: [2, 1, 2, 2, 1, 2, 2],
    chord: 'm7',
    desc: 'Mineur naturel',
    category: 'classique_mineur',
    examples: [
      { song: 'Stairway to Heaven', artist: 'Led Zeppelin', note: 'Am aeolien' },
      { song: 'Comfortably Numb', artist: 'Pink Floyd', note: 'Bm aeolien' },
      { song: 'Nothing Else Matters', artist: 'Metallica', note: 'Em aeolien' },
    ],
  },
  {
    key: 'locrian',
    name: 'Locrien',
    intervals: [1, 2, 2, 1, 2, 2, 2],
    chord: 'm7b5',
    desc: 'Demi-diminué, instable',
    category: 'classique_mineur',
    examples: [
      { song: 'The Grudge', artist: 'Tool', note: 'E locrien' },
      { song: 'YYZ', artist: 'Rush', note: 'sections en locrien' },
      { song: 'utilisé théoriquement sur les accords vii°', artist: 'Jazz (général)' },
    ],
  },
  // ── Blues & Pentatoniques ──
  {
    key: 'pentatonic_major',
    name: 'Pentatonique majeure',
    intervals: [2, 2, 3, 2, 3],
    chord: 'maj7',
    desc: 'Sons country/folk',
    category: 'blues',
    examples: [
      { song: 'My Girl', artist: 'The Temptations', note: 'C penta. maj.' },
      { song: 'Country Roads', artist: 'John Denver', note: 'G penta. maj.' },
      { song: 'Oh! Susanna', artist: 'traditionnel' },
    ],
  },
  {
    key: 'pentatonic_minor',
    name: 'Pentatonique mineure',
    intervals: [3, 2, 2, 3, 2],
    chord: 'm7',
    desc: 'La base du blues/rock',
    category: 'blues',
    examples: [
      { song: 'Smoke on the Water', artist: 'Deep Purple', note: 'G min pentatonique' },
      { song: 'Purple Haze', artist: 'Jimi Hendrix', note: 'E min pentatonique' },
      { song: 'Crazy Train', artist: 'Ozzy / Randy Rhoads', note: 'F# min pentatonique' },
    ],
  },
  {
    key: 'blues_major',
    name: 'Blues majeure',
    intervals: [2, 1, 1, 3, 2, 3],
    chord: '7',
    desc: 'Le son blues classique',
    category: 'blues',
    examples: [
      { song: 'Johnny B. Goode', artist: 'Chuck Berry', note: 'Bb blues maj.' },
      { song: 'Roll Over Beethoven', artist: 'Chuck Berry' },
      { song: 'Good Golly Miss Molly', artist: 'Little Richard' },
    ],
  },
  {
    key: 'blues_minor',
    name: 'Blues mineure',
    intervals: [3, 2, 1, 1, 3, 2],
    chord: 'm7',
    desc: 'Pentatonique + blue note',
    category: 'blues',
    examples: [
      { song: 'Red House', artist: 'Jimi Hendrix', note: 'B blues min.' },
      { song: 'The Thrill Is Gone', artist: 'B.B. King', note: 'B blues min.' },
      { song: 'La Grange', artist: 'ZZ Top', note: 'A blues min.' },
    ],
  },
  // ── Jazz & Avancé ──
  {
    key: 'melodic_minor',
    name: 'Mineur mélodique',
    intervals: [2, 1, 2, 2, 2, 2, 1],
    chord: 'mMaj7',
    desc: "Jazz minor — base de l'impro moderne",
    category: 'jazz',
    examples: [
      { song: 'Footprints', artist: 'Wayne Shorter', note: 'Cm mineur mélodique' },
      { song: 'Solar', artist: 'Miles Davis', note: 'jazz modal' },
      { song: 'base de l\'harmonie jazz moderne', artist: 'Bill Evans / Chick Corea' },
    ],
  },
  {
    key: 'harmonic_minor',
    name: 'Mineur harmonique',
    intervals: [2, 1, 2, 2, 1, 3, 1],
    chord: 'mMaj7',
    desc: 'Seconde augmentée caractéristique',
    category: 'jazz',
    examples: [
      { song: 'Moonlight Sonata (mvt. 3)', artist: 'Beethoven', note: 'C# harm. min.' },
      { song: 'Eruption', artist: 'Van Halen', note: 'sections harm. mineure' },
      { song: 'Fiddler on the Roof', artist: 'Jerry Bock', note: 'couleur klezmer/harm. min.' },
    ],
  },
  {
    key: 'altered',
    name: 'Altered',
    intervals: [1, 2, 1, 2, 2, 2, 2],
    chord: '7alt',
    desc: 'Tension max, outside',
    category: 'jazz',
    examples: [
      { song: 'impro sur accords dominants', artist: 'John Coltrane / Charlie Parker', note: 'tension → résolution' },
      { song: 'Giant Steps', artist: 'John Coltrane', note: 'altered sur les V7' },
      { song: 'A Love Supreme', artist: 'John Coltrane', note: 'altered alterné' },
    ],
  },
  {
    key: 'lydian_dom',
    name: 'Lydien dominante',
    intervals: [2, 2, 2, 1, 2, 1, 2],
    chord: '7#11',
    desc: 'Brillant, #4 + b7',
    category: 'jazz',
    examples: [
      { song: 'The Simpsons Theme', artist: 'Danny Elfman', note: 'C lydien dominant' },
      { song: 'Maiden Voyage', artist: 'Herbie Hancock', note: 'couleur lydien dom.' },
      { song: 'solos fusion', artist: 'Joe Satriani / John Scofield' },
    ],
  },
  {
    key: 'lydian_aug',
    name: 'Lydien augmenté',
    intervals: [2, 2, 2, 2, 1, 2, 1],
    chord: 'maj7#5',
    desc: 'Mode 3 du mél. mineur, très flottant',
    category: 'jazz',
    examples: [
      { song: 'musique impressionniste', artist: 'Ravel / Debussy', note: 'flottant, ambigu' },
      { song: 'jazz fusion moderne', artist: 'Allan Holdsworth' },
    ],
  },
  {
    key: 'mixolydian_b6',
    name: 'Mixolydien b6',
    intervals: [2, 2, 1, 2, 1, 2, 2],
    chord: '7b6',
    desc: 'Mode 5 du mél. mineur',
    category: 'jazz',
    examples: [
      { song: 'jazz modern (sur V7b13)', artist: 'McCoy Tyner', note: 'couleur modale' },
    ],
  },
  {
    key: 'locrian_2',
    name: 'Locrien #2',
    intervals: [2, 1, 2, 1, 2, 2, 2],
    chord: 'm7b5',
    desc: 'Demi-diminué jazz — sur les m7b5',
    category: 'jazz',
    examples: [
      { song: 'Autumn Leaves', artist: 'jazz standard', note: 'sur les accords iim7b5' },
      { song: 'Speak No Evil', artist: 'Wayne Shorter', note: 'locrien #2' },
    ],
  },
  {
    key: 'phrygian_dom',
    name: 'Phrygien dominant',
    intervals: [1, 3, 1, 2, 1, 2, 2],
    chord: '7b9',
    desc: 'Mode 5 du harm. mineur — son flamenco/jazz',
    category: 'jazz',
    examples: [
      { song: 'flamenco (rumba, soleares)', artist: 'Paco de Lucía', note: 'E phrygien dom.' },
      { song: 'La Bamba', artist: 'Ritchie Valens', note: 'son jarocho mexicain' },
      { song: 'Hava Nagila', artist: 'traditionnel', note: 'musique hébraïque' },
    ],
  },
  {
    key: 'bebop_dom',
    name: 'Bebop dominant',
    intervals: [2, 2, 1, 2, 2, 1, 1, 2],
    chord: '7',
    desc: '8 notes — le son bebop',
    category: 'jazz',
    examples: [
      { song: 'Anthropology', artist: 'Charlie Parker', note: '8 notes, phrases sur les temps forts' },
      { song: 'Donna Lee', artist: 'Charlie Parker / Miles Davis' },
      { song: 'Groovin\' High', artist: 'Dizzy Gillespie' },
    ],
  },
  // ── Symétriques ──
  {
    key: 'whole_tone',
    name: 'Gamme par tons',
    intervals: [2, 2, 2, 2, 2, 2],
    chord: '7#5',
    desc: '6 notes, ambiguïté tonale totale',
    category: 'symetrique',
    examples: [
      { song: 'Voiles', artist: 'Claude Debussy', note: 'Préludes pour piano, livre I' },
      { song: 'Whole Lotta Love', artist: 'Led Zeppelin', note: 'section centrale psychédélique' },
      { song: 'improvisation sur les dom7#5', artist: 'Thelonious Monk / Herbie Hancock' },
    ],
  },
  {
    key: 'half_whole',
    name: 'Diminué ½T/T',
    intervals: [1, 2, 1, 2, 1, 2, 1, 2],
    chord: '7b9',
    desc: '8 notes, très chromatique',
    category: 'symetrique',
    examples: [
      { song: 'sur les accords dom7b9', artist: 'John Scofield / Pat Metheny', note: 'jazz et fusion' },
      { song: 'Mode 2 de Messiaen', artist: 'Olivier Messiaen', note: 'Quatuor pour la fin du temps' },
    ],
  },
  {
    key: 'whole_half',
    name: 'Diminué T/½T',
    intervals: [2, 1, 2, 1, 2, 1, 2, 1],
    chord: 'dim7',
    desc: '8 notes — sur les accords diminués',
    category: 'symetrique',
    examples: [
      { song: 'sur les accords dim7', artist: 'Django Reinhardt', note: 'gypsy jazz' },
      { song: 'ballet et orchestre', artist: 'Igor Stravinsky', note: 'couleur dramatique' },
    ],
  },
  // ── Exotiques ──
  {
    key: 'rock_n_roll',
    name: 'Rock n Roll',
    intervals: [2, 1, 1, 3, 2, 3],
    chord: '7',
    desc: '1–2–b3–3–5–6 — la pentatonique majeure + blue note',
    category: 'exotique',
    examples: [
      { song: 'Johnny B. Goode (riffs)', artist: 'Chuck Berry', note: 'base du rockabilly' },
      { song: 'Rock Around the Clock', artist: 'Bill Haley & His Comets' },
      { song: 'Blue Suede Shoes', artist: 'Elvis Presley' },
    ],
  },
  {
    key: 'bebop_dorian',
    name: 'Bebop Dorien',
    intervals: [2, 1, 2, 2, 2, 1, 1, 1],
    chord: 'm7',
    desc: '8 notes — Dorien + maj7 chromatique',
    category: 'exotique',
    examples: [
      { song: 'impro jazz sur im7 / iim7', artist: 'Wes Montgomery / Joe Pass' },
      { song: 'So What (variante)', artist: 'Miles Davis', note: 'phrases bebop en dorien' },
    ],
  },
  {
    key: 'bebop_mixolydian',
    name: 'Bebop Mixolydien',
    intervals: [2, 2, 1, 2, 2, 1, 1, 1],
    chord: '7',
    desc: '8 notes — Mixolydien + maj7 chromatique',
    category: 'exotique',
    examples: [
      { song: 'impro bebop sur V7', artist: 'Charlie Christian', note: 'guitare jazz swing' },
      { song: 'How High the Moon', artist: 'jazz standard', note: 'bebop mixolydien sur G7' },
    ],
  },
  {
    key: 'persian',
    name: 'Persane',
    intervals: [1, 3, 1, 1, 2, 3, 1],
    chord: 'maj7b5',
    desc: '1–b2–3–4–b5–b6–7 — couleur Proche-Orient',
    category: 'exotique',
    examples: [
      { song: 'The Attitude Song', artist: 'Steve Vai', note: 'gamme persane explicite' },
      { song: 'musique classique persane', artist: 'Shajarian (traditionnel)', note: 'dastgah Shur' },
    ],
  },
  {
    key: 'gypsy_major',
    name: 'Tsigane majeure',
    intervals: [1, 3, 1, 2, 1, 3, 1],
    chord: 'maj7',
    desc: '1–b2–3–4–5–b6–7 — Byzantine, double harmonique',
    category: 'exotique',
    examples: [
      { song: 'musique balkanique (generale)', artist: 'traditions bulgare / hongroise', note: 'double harmonique' },
      { song: 'Minor Swing (influences)', artist: 'Django Reinhardt', note: 'couleur tsigane' },
    ],
  },
  {
    key: 'gypsy_minor',
    name: 'Tsigane mineure',
    intervals: [2, 1, 3, 1, 1, 3, 1],
    chord: 'mMaj7',
    desc: '1–2–b3–#4–5–b6–7 — Hongroise, dramatique',
    category: 'exotique',
    examples: [
      { song: 'Minor Swing', artist: 'Django Reinhardt', note: 'Am tsigane mineure' },
      { song: 'Hungarian Rhapsody No. 2', artist: 'Franz Liszt', note: 'gamme hongroise' },
      { song: 'musique klezmer', artist: 'Giora Feidman', note: 'tradition ashkénaze' },
    ],
  },
  // ── Arpeggios ──
  {
    key: 'arp_maj',
    name: 'Arp. Majeur',
    intervals: [4, 3, 5],
    chord: '',
    desc: 'Triode majeure 1–3–5',
    category: 'arpege',
    letterOffsets: [0, 2, 4],
  },
  {
    key: 'arp_min',
    name: 'Arp. Mineur',
    intervals: [3, 4, 5],
    chord: 'm',
    desc: 'Triode mineure 1–b3–5',
    category: 'arpege',
    letterOffsets: [0, 2, 4],
  },
  {
    key: 'arp_dom7',
    name: 'Arp. Dom7',
    intervals: [4, 3, 3, 2],
    chord: '7',
    desc: 'Dominante 1–3–5–b7',
    category: 'arpege',
    letterOffsets: [0, 2, 4, 6],
  },
  {
    key: 'arp_maj7',
    name: 'Arp. Maj7',
    intervals: [4, 3, 4, 1],
    chord: 'maj7',
    desc: 'Majeur 7e 1–3–5–7',
    category: 'arpege',
    letterOffsets: [0, 2, 4, 6],
  },
  {
    key: 'arp_m7',
    name: 'Arp. m7',
    intervals: [3, 4, 3, 2],
    chord: 'm7',
    desc: 'Mineur 7e 1–b3–5–b7',
    category: 'arpege',
    letterOffsets: [0, 2, 4, 6],
  },
  {
    key: 'arp_m7b5',
    name: 'Arp. m7b5',
    intervals: [3, 3, 4, 2],
    chord: 'm7b5',
    desc: 'Demi-diminué 1–b3–b5–b7',
    category: 'arpege',
    letterOffsets: [0, 2, 4, 6],
  },
  {
    key: 'arp_dim7',
    name: 'Arp. dim7',
    intervals: [3, 3, 3, 3],
    chord: 'dim7',
    desc: 'Diminué 7e 1–b3–b5–bb7',
    category: 'arpege',
    letterOffsets: [0, 2, 4, 6],
  },
  {
    key: 'arp_mmaj7',
    name: 'Arp. mMaj7',
    intervals: [3, 4, 4, 1],
    chord: 'mMaj7',
    desc: 'Mineur majeur 7e 1–b3–5–7',
    category: 'arpege',
    letterOffsets: [0, 2, 4, 6],
  },
];

export const MODES_BY_KEY = new Map<ModeKey, Mode>(
  MODES.map((m) => [m.key, m]),
);

export function getMode(key: ModeKey): Mode {
  const mode = MODES_BY_KEY.get(key);
  if (!mode) throw new Error(`Mode inconnu: ${key}`);
  return mode;
}
